/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/disk/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan */
        get: operations["scan_api_disk_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan */
        get: operations["scan_api_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recipe */
        post: operations["recipe_api_recipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/disk-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk Dashboard Summary */
        get: operations["disk_dashboard_summary_api_dashboard_disk_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_snapshots_get"];
        put?: never;
        /** Create Snapshot */
        post: operations["create_snapshot_api_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_api_snapshots__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Timeline
         * @description Merged audit timeline: cleanup events + snapshot creations, newest-first.
         */
        get: operations["history_timeline_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff */
        get: operations["diff_api_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clean/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Job */
        post: operations["start_job_api_clean_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clean/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_clean_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clean/jobs/{job_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_api_clean_jobs__job_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clean/jobs/{job_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_clean_jobs__job_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clean/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_clean_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disk-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk Usage */
        get: operations["disk_usage_api_disk_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory */
        get: operations["memory_api_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory History */
        get: operations["memory_history_api_memory_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memory Snapshots */
        get: operations["list_memory_snapshots_api_memory_snapshots_get"];
        put?: never;
        /** Create Memory Snapshot */
        post: operations["create_memory_snapshot_api_memory_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/snapshots/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Memory Snapshots */
        get: operations["diff_memory_snapshots_api_memory_snapshots_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/snapshots/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory Snapshot */
        get: operations["get_memory_snapshot_api_memory_snapshots__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Sources */
        get: operations["memory_sources_api_memory_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Providers */
        get: operations["memory_providers_api_memory_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/workloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Workloads */
        get: operations["memory_workloads_api_memory_workloads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Plan */
        post: operations["memory_plan_api_memory_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Action */
        post: operations["memory_action_api_memory_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppSettingsInfo */
        AppSettingsInfo: {
            /**
             * Storage Backend
             * @enum {string}
             */
            storage_backend: "filesystem" | "sqlite";
            /** Data Dir */
            data_dir: string;
            /** Sqlite Path */
            sqlite_path: string;
            /** Available Backends */
            available_backends: ("filesystem" | "sqlite")[];
        };
        /** AppSettingsPatch */
        AppSettingsPatch: {
            /** Storage Backend */
            storage_backend?: ("filesystem" | "sqlite") | null;
            /** Data Dir */
            data_dir?: string | null;
            /** Sqlite Path */
            sqlite_path?: string | null;
        };
        /** CleanJobCreate */
        CleanJobCreate: {
            /** Entry Ids */
            entry_ids: string[];
            /**
             * Yes Safe
             * @default false
             */
            yes_safe: boolean;
            /**
             * Allow Dangerous
             * @default false
             */
            allow_dangerous: boolean;
        };
        /** ConfirmAnswer */
        ConfirmAnswer: {
            /** Confirmed */
            confirmed: boolean;
        };
        /** DiskDashboardEntryInfo */
        DiskDashboardEntryInfo: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Label */
            label: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Risk
             * @enum {string}
             */
            risk: "safe" | "reclaimable" | "dangerous";
        };
        /** DiskDashboardProviderTotalInfo */
        DiskDashboardProviderTotalInfo: {
            /** Provider */
            provider: string;
            /** Bytes */
            bytes: number;
            /** Count */
            count: number;
        };
        /** DiskDashboardSummaryInfo */
        DiskDashboardSummaryInfo: {
            /** Scanned At */
            scanned_at: string;
            /** Hostname */
            hostname: string;
            /** Platform */
            platform: string;
            /** Total Bytes */
            total_bytes: number;
            /** Entry Count */
            entry_count: number;
            /** Entries */
            entries?: components["schemas"]["DiskDashboardEntryInfo"][];
            /** Provider Totals */
            provider_totals?: components["schemas"]["DiskDashboardProviderTotalInfo"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MemoryActionExecuteRequest */
        MemoryActionExecuteRequest: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "inspect_browser" | "discard_tabs" | "stop_container" | "stop_service" | "quit_app" | "terminate_process";
            /** Target Id */
            target_id: string;
            /** Label */
            label?: string | null;
            /** Estimated Bytes */
            estimated_bytes?: number | null;
            /** Risk */
            risk?: ("safe" | "reclaimable" | "dangerous") | null;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /** MemoryActionExecuteResultInfo */
        MemoryActionExecuteResultInfo: {
            /** Action Id */
            action_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error" | "unsupported";
            /** Message */
            message: string;
        };
        /** MemoryActionInfo */
        MemoryActionInfo: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "inspect_browser" | "discard_tabs" | "stop_container" | "stop_service" | "quit_app" | "terminate_process";
            /** Label */
            label: string;
            /** Target Id */
            target_id: string;
            /** Estimated Bytes */
            estimated_bytes: number | null;
            /**
             * Risk
             * @enum {string}
             */
            risk: "safe" | "reclaimable" | "dangerous";
        };
        /** MemoryConsumerInfo */
        MemoryConsumerInfo: {
            /** Id */
            id: string;
            /** Pid */
            pid: number | null;
            /** Parent Pid */
            parent_pid: number | null;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "app" | "process" | "browser" | "electron" | "docker" | "llm" | "other";
            /** Rss Bytes */
            rss_bytes: number;
            /** Private Bytes */
            private_bytes: number | null;
            /** Command */
            command: string | null;
            /** Children */
            children?: components["schemas"]["MemoryConsumerInfo"][];
        };
        /** MemoryHistoryInfo */
        MemoryHistoryInfo: {
            /** Observations */
            observations: components["schemas"]["MemoryObservationMetaInfo"][];
        };
        /** MemoryObservationMetaInfo */
        MemoryObservationMetaInfo: {
            /** Id */
            id: string;
            /** Scanned At */
            scanned_at: string;
            /**
             * Pressure
             * @enum {string}
             */
            pressure: "ok" | "warn" | "critical" | "unknown";
            /** Total Bytes */
            total_bytes: number;
            /** Available Bytes */
            available_bytes: number;
            /** Used Bytes */
            used_bytes: number;
            /** Swap Used Bytes */
            swap_used_bytes: number | null;
            /** Compressed Bytes */
            compressed_bytes: number | null;
            /** Top Consumer Name */
            top_consumer_name: string | null;
            /** Top Consumer Kind */
            top_consumer_kind: ("app" | "process" | "browser" | "electron" | "docker" | "llm" | "other") | null;
            /** Top Consumer Rss Bytes */
            top_consumer_rss_bytes: number | null;
            /** Suggestion Count */
            suggestion_count: number;
        };
        /** MemoryPlanActionInfo */
        MemoryPlanActionInfo: {
            /** Suggestion Id */
            suggestion_id: string;
            /** Action Id */
            action_id: string;
            /** Label */
            label: string;
            /** Estimated Bytes */
            estimated_bytes: number | null;
            /**
             * Risk
             * @enum {string}
             */
            risk: "safe" | "reclaimable" | "dangerous";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
        };
        /** MemoryPlanInfo */
        MemoryPlanInfo: {
            workload: components["schemas"]["MemoryWorkloadInfo"];
            /** Fits Now */
            fits_now: boolean;
            /** Required Bytes */
            required_bytes: number;
            /** Available Bytes */
            available_bytes: number;
            /** Os Reserve Bytes */
            os_reserve_bytes: number;
            /** Safety Margin Bytes */
            safety_margin_bytes: number;
            /** Usable Bytes */
            usable_bytes: number;
            /** Deficit Bytes */
            deficit_bytes: number;
            /** Planned Reclaim Bytes */
            planned_reclaim_bytes: number;
            /** Remaining Deficit Bytes */
            remaining_deficit_bytes: number;
            /** Actions */
            actions: components["schemas"]["MemoryPlanActionInfo"][];
        };
        /** MemoryPlanRequest */
        MemoryPlanRequest: {
            /** Workload Id */
            workload_id?: string | null;
            /** Custom Label */
            custom_label?: string | null;
            /** Custom Required Bytes */
            custom_required_bytes?: number | null;
            /** Safety Margin Bytes */
            safety_margin_bytes?: number | null;
            /** Providers */
            providers?: string[] | null;
        };
        /** MemoryProviderInfo */
        MemoryProviderInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "browser" | "electron" | "docker" | "llm" | "app" | "process";
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "unavailable" | "planned";
            /** Description */
            description: string;
            /** Detail */
            detail?: string | null;
            /** Consumer Kinds */
            consumer_kinds: ("app" | "process" | "browser" | "electron" | "docker" | "llm" | "other")[];
        };
        /** MemoryProviderTotalInfo */
        MemoryProviderTotalInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "browser" | "electron" | "docker" | "llm" | "app" | "process";
            /** Selected */
            selected: boolean;
            /** Rss Bytes */
            rss_bytes: number;
            /** Consumer Count */
            consumer_count: number;
        };
        /** MemoryReportInfo */
        MemoryReportInfo: {
            /** Scanned At */
            scanned_at: string;
            /** Hostname */
            hostname: string;
            /** Platform */
            platform: string;
            system: components["schemas"]["SystemMemoryInfo"];
            /** Consumers */
            consumers: components["schemas"]["MemoryConsumerInfo"][];
            /** Provider Totals */
            provider_totals?: components["schemas"]["MemoryProviderTotalInfo"][];
            /** Suggestions */
            suggestions?: components["schemas"]["MemorySuggestionInfo"][];
        };
        /** MemorySnapshotCreate */
        MemorySnapshotCreate: {
            /** Note */
            note?: string | null;
        };
        /** MemorySnapshotDiffInfo */
        MemorySnapshotDiffInfo: {
            before: components["schemas"]["MemorySnapshotMetaInfo"];
            after: components["schemas"]["MemorySnapshotMetaInfo"];
            /** Available Delta Bytes */
            available_delta_bytes: number;
            /** Used Delta Bytes */
            used_delta_bytes: number;
            /** Swap Delta Bytes */
            swap_delta_bytes: number | null;
            /** Compressed Delta Bytes */
            compressed_delta_bytes: number | null;
            /** Top Consumer Deltas */
            top_consumer_deltas: {
                [key: string]: unknown;
            }[];
            /** Added Suggestion Ids */
            added_suggestion_ids: string[];
            /** Removed Suggestion Ids */
            removed_suggestion_ids: string[];
        };
        /** MemorySnapshotInfo */
        MemorySnapshotInfo: {
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** Note */
            note: string | null;
            report: components["schemas"]["MemoryReportInfo"];
        };
        /** MemorySnapshotMetaInfo */
        MemorySnapshotMetaInfo: {
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** Scanned At */
            scanned_at: string;
            /** Note */
            note: string | null;
            /**
             * Pressure
             * @enum {string}
             */
            pressure: "ok" | "warn" | "critical" | "unknown";
            /** Total Bytes */
            total_bytes: number;
            /** Available Bytes */
            available_bytes: number;
            /** Used Bytes */
            used_bytes: number;
            /** Top Consumer Name */
            top_consumer_name: string | null;
            /** Top Consumer Kind */
            top_consumer_kind: ("app" | "process" | "browser" | "electron" | "docker" | "llm" | "other") | null;
            /** Top Consumer Rss Bytes */
            top_consumer_rss_bytes: number | null;
        };
        /** MemorySourceInfo */
        MemorySourceInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "system" | "process" | "docker" | "llm" | "browser";
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "unavailable" | "planned";
            /** Description */
            description: string;
            /** Detail */
            detail?: string | null;
        };
        /** MemorySuggestionInfo */
        MemorySuggestionInfo: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Reason */
            reason: string;
            /** Estimated Bytes */
            estimated_bytes: number | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Actions */
            actions?: components["schemas"]["MemoryActionInfo"][];
        };
        /** MemoryWorkloadInfo */
        MemoryWorkloadInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "llm" | "docker" | "browser" | "developer" | "custom";
            /** Required Bytes */
            required_bytes: number;
            /** Description */
            description: string;
        };
        /** PromptAnswer */
        PromptAnswer: {
            /** Entry Id */
            entry_id: string;
            /**
             * Choice
             * @enum {string}
             */
            choice: "y" | "n" | "a" | "s" | "q";
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Risk
             * @enum {string}
             */
            risk: "safe" | "reclaimable" | "dangerous";
            /** Platforms */
            platforms: string[];
            /** Available */
            available: boolean;
            /** Required Binary */
            required_binary: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "class" | "yaml";
            /** Reason If Unavailable */
            reason_if_unavailable?: string | null;
            /** Details */
            details?: string | null;
            /** Raw Paths */
            raw_paths?: string[] | null;
            /** Resolved Paths */
            resolved_paths?: string[] | null;
            /** Recipe Template */
            recipe_template?: string[] | null;
        };
        /** RecipeRequest */
        RecipeRequest: {
            /** Providers */
            providers?: string[] | null;
        };
        /** RecipeResponse */
        RecipeResponse: {
            /** Script */
            script: string;
        };
        /** SnapshotCreate */
        SnapshotCreate: {
            /** Note */
            note?: string | null;
        };
        /** SnapshotMeta */
        SnapshotMeta: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Scanned At */
            scanned_at: string;
            /** Hostname */
            hostname: string;
            /** Platform */
            platform: string;
            /** Note */
            note: string | null;
            /** Total Bytes */
            total_bytes: number;
            /**
             * Kind
             * @default manual
             * @enum {string}
             */
            kind: "auto" | "manual";
            /** Duration Ms */
            duration_ms?: number | null;
            /** Entry Count */
            entry_count?: number | null;
            /** Per Provider */
            per_provider?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** SystemMemoryInfo */
        SystemMemoryInfo: {
            /** Total Bytes */
            total_bytes: number;
            /** Available Bytes */
            available_bytes: number;
            /** Used Bytes */
            used_bytes: number;
            /** Swap Used Bytes */
            swap_used_bytes: number | null;
            /** Compressed Bytes */
            compressed_bytes: number | null;
            /**
             * Pressure
             * @enum {string}
             */
            pressure: "ok" | "warn" | "critical" | "unknown";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scan_api_disk_scan_get: {
        parameters: {
            query?: {
                min_size?: string | null;
                risk?: string | null;
                provider?: string | null;
                snapshot?: boolean;
                snapshot_min_interval_ms?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_api_scan_get: {
        parameters: {
            query?: {
                min_size?: string | null;
                risk?: string | null;
                provider?: string | null;
                snapshot?: boolean;
                snapshot_min_interval_ms?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfo"][];
                };
            };
        };
    };
    recipe_api_recipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disk_dashboard_summary_api_dashboard_disk_summary_get: {
        parameters: {
            query?: {
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskDashboardSummaryInfo"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_snapshots_get: {
        parameters: {
            query?: {
                limit?: number | null;
                kind?: "auto" | "manual" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotMeta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_snapshot_api_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_snapshots__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_timeline_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_api_diff_get: {
        parameters: {
            query: {
                from_: string;
                to_: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_api_clean_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_clean_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_clean_jobs__job_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptAnswer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_clean_jobs__job_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmAnswer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_clean_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disk_usage_api_disk_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    memory_api_memory_get: {
        parameters: {
            query?: {
                record?: boolean;
                record_min_interval_ms?: number | null;
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryReportInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_history_api_memory_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryHistoryInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memory_snapshots_api_memory_snapshots_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySnapshotMetaInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memory_snapshot_api_memory_snapshots_post: {
        parameters: {
            query?: {
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorySnapshotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySnapshotMetaInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_memory_snapshots_api_memory_snapshots_diff_get: {
        parameters: {
            query: {
                from_: string;
                to_: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySnapshotDiffInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_snapshot_api_memory_snapshots__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySnapshotInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_sources_api_memory_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySourceInfo"][];
                };
            };
        };
    };
    memory_providers_api_memory_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProviderInfo"][];
                };
            };
        };
    };
    memory_workloads_api_memory_workloads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryWorkloadInfo"][];
                };
            };
        };
    };
    memory_plan_api_memory_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryPlanInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_action_api_memory_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryActionExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryActionExecuteResultInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsInfo"];
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
